# The Beginning - All about data

## Load Basic Libraries

In [21]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns',None)

In [22]:
import warnings
warnings.filterwarnings('ignore')

## Load the data

In [23]:
df = pd.read_csv('/kaggle/input/kagglex-bipoc-2022-2023-ml-foundation/Train.csv')

In [24]:
df.rename(columns = {
#             'ID': , 
            'AAGE': 'age', 
            'ACLSWKR': 'class of worker', 
            'ADTIND': 'industry code', 
            'ADTOCC': 'occupation code', 
            'AHGA':'education', 
            'AHRSPAY':'wage per hour',
            'AHSCOL':'enrolled in edu inst last wk', 
            'AMARITL':'marital status', 
            'AMJIND':'major industry code', 
            'AMJOCC':'major occupation code', 
            'ARACE':'race', 
            'AREORGN':'hispanic origin', 
            'ASEX':'gender',
            'AUNMEM':'member of a labor union', 
            'AUNTYPE':'reason for unemployment', 
            'AWKSTAT':'full or part time employment stat', 
            'CAPGAIN':'capital gains', 
            'CAPLOSS':'capital losses', 
            'DIVVAL':'divdends from stocks',
            'FILESTAT': 'tax filer status', 
            'GRINREG':'region of previous residence', 
            'GRINST':'state of previous residence', 
            'HHDFMX':'detailed household and family stat', 
            'HHDREL':'detailed household summary in household', 
            'MIGMTR1':'migration code-change in msa',
            'MIGMTR3':'migration code-change in reg', 
            'MIGMTR4':'migration code-move within reg', 
            'MIGSAME':'live in this house 1 year ago', 
            'MIGSUN':'migration prev res in sunbelt', 
            'NOEMP':'num persons worked for employer', 
            'PARENT':'family members under 18',
            'PEFNTVTY':'country of birth father', 
            'PEMNTVTY':'country of birth mother', 
            'PENATVTY':'country of birth self', 
            'PRCITSHP':'citizenship', 
            'SEOTR':'own business or self employed', 
            'VETQVA':'fill inc questionnaire for veteran\'s admin',
            'VETYN':'veterans benefits', 
            'WKSWORK':'weeks worked in year', 
#             'YEAR', 
#             'TARGET'    
}, inplace=True)

In [25]:
df.head()

,ID,age,class of worker,industry code,occupation code,education,wage per hour,enrolled in edu inst last wk,marital status,major industry code,major occupation code,race,hispanic origin,gender,member of a labor union,reason for unemployment,full or part time employment stat,capital gains,capital losses,divdends from stocks,tax filer status,region of previous residence,state of previous residence,detailed household and family stat,detailed household summary in household,migration code-change in msa,migration code-change in reg,migration code-move within reg,live in this house 1 year ago,migration prev res in sunbelt,num persons worked for employer,family members under 18,country of birth father,country of birth mother,country of birth self,citizenship,own business or self employed,fill inc questionnaire for veteran's admin,veterans benefits,weeks worked in year,YEAR,TARGET
0,shydl6zxik4o,22,Not in universe,0,0,High school graduate,0,Not in universe,Divorced,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Single,Not in universe,Not in universe,Secondary individual,Nonrelative of householder,NaN,NaN,NaN,Not in universe under 1 year old,NaN,1,Not in universe,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,36,1995,0
1,2dhm421r62rr,37,Private,35,33,Some college but no degree,0,Not in universe,Divorced,Finance insurance and real estate,Precision production craft & repair,White,All other,Male,Not in universe,Not in universe,Full-time schedules,0,0,0,Single,Not in universe,Not in universe,Nonfamily householder,Householder,NaN,NaN,NaN,Not in universe under 1 year old,NaN,1,Not in universe,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,47,1995,0
2,ys7nzza2hffj,83,Not in universe,0,0,1st 2nd 3rd or 4th grade,0,Not in universe,Widowed,Not in universe or children,Not in universe,White,Puerto Rican,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Nonfamily householder,Householder,NaN,NaN,NaN,Not in universe under 1 year old,NaN,0,Not in universe,Puerto-Rico,Puerto-Rico,Puerto-Rico,Native- Born in Puerto Rico or U S Outlying,0,Not in universe,2,0,1995,0
3,iqrpxh3sr7n1,46,Private,32,35,High school graduate,0,Not in universe,Married-civilian spouse present,Wholesale trade,Precision production craft & repair,White,All other,Male,Not in universe,Not in universe,Full-time schedules,0,0,1800,Joint both under 65,Not in universe,Not in universe,Householder,Householder,NaN,NaN,NaN,Not in universe under 1 year old,NaN,1,Not in universe,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,1995,0
4,rr8vlzk9iwyn,35,Private,34,26,Associates degree-academic program,0,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Adm support including clerical,White,All other,Female,Not in universe,Not in universe,Full-time schedules,0,0,0,Joint both under 65,Not in universe,Not in universe,Spouse of householder,Spouse of householder,NaN,NaN,NaN,Not in universe under 1 year old,NaN,6,Not in universe,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,45,1995,0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157509 entries, 0 to 157508
Data columns (total 42 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   ID                                          157509 non-null  object
 1   age                                         157509 non-null  int64
 2   class of worker                             157509 non-null  object
 3   industry code                               157509 non-null  int64
 4   occupation code                             157509 non-null  int64
 5   education                                   157509 non-null  object
 6   wage per hour                               157509 non-null  int64
 7   enrolled in edu inst last wk                157509 non-null  object
 8   marital status                              157509 non-null  object
 9   major industry code                         157509 non-null  object
 10  major occupation code                       157509 non-null  object
 11  race                                        157509 non-null  object
 12  hispanic origin                             157509 non-null  object
 13  gender                                      157509 non-null  object
 14  member of a labor union                     157509 non-null  object
 15  reason for unemployment                     157509 non-null  object
 16  full or part time employment stat           157509 non-null  object
 17  capital gains                               157509 non-null  int64
 18  capital losses                              157509 non-null  int64
 19  divdends from stocks                        157509 non-null  int64
 20  tax filer status                            157509 non-null  object
 21  region of previous residence                157509 non-null  object
 22  state of previous residence                 156809 non-null  object
 23  detailed household and family stat          157509 non-null  object
 24  detailed household summary in household     157509 non-null  object
 25  migration code-change in msa                80189 non-null   object
 26  migration code-change in reg                80189 non-null   object
 27  migration code-move within reg              80189 non-null   object
 28  live in this house 1 year ago               157509 non-null  object
 29  migration prev res in sunbelt               80189 non-null   object
 30  num persons worked for employer             157509 non-null  int64
 31  family members under 18                     157509 non-null  object
 32  country of birth father                     150906 non-null  object
 33  country of birth mother                     151501 non-null  object
 34  country of birth self                       154013 non-null  object
 35  citizenship                                 157509 non-null  object
 36  own business or self employed               157509 non-null  int64
 37  fill inc questionnaire for veteran's admin  157509 non-null  object
 38  veterans benefits                           157509 non-null  int64
 39  weeks worked in year                        157509 non-null  int64
 40  YEAR                                        157509 non-null  int64
 41  TARGET                                      157509 non-null  int64
dtypes: int64(13), object(29)
memory usage: 50.5+ MB

In [27]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,157509.0,39.816112,19.404058,0.0,26.0,38.0,52.0,90.0
industry code,157509.0,20.308440,18.183850,0.0,0.0,24.0,37.0,51.0
occupation code,157509.0,14.971830,14.890825,0.0,0.0,12.0,29.0,46.0
wage per hour,157509.0,72.889797,311.546534,0.0,0.0,0.0,0.0,9916.0
capital gains,157509.0,577.585992,5403.024319,0.0,0.0,0.0,0.0,99999.0
capital losses,157509.0,49.300015,311.199032,0.0,0.0,0.0,0.0,4608.0
divdends from stocks,157509.0,264.806386,2282.967898,0.0,0.0,0.0,0.0,99999.0
num persons worked for employer,157509.0,2.580913,2.400063,0.0,0.0,2.0,5.0,6.0
own business or self employed,157509.0,0.234825,0.629650,0.0,0.0,0.0,0.0,2.0
veterans benefits,157509.0,1.834517,0.538978,0.0,2.0,2.0,2.0,2.0
weeks worked in year,157509.0,30.600182,23.635018,0.0,0.0,48.0,52.0,52.0
YEAR,157509.0,1994.490893,0.499919,1994.0,1994.0,1994.0,1995.0,1995.0
TARGET,157509.0,0.082408,0.274986,0.0,0.0,0.0,0.0,1.0

In [28]:
df.nunique()

ID                                            157509
age                                               91
class of worker                                    9
industry code                                     52
occupation code                                   47
education                                         17
wage per hour                                   1275
enrolled in edu inst last wk                       3
marital status                                     7
major industry code                               24
major occupation code                             15
race                                               5
hispanic origin                                   10
gender                                             2
member of a labor union                            3
reason for unemployment                            6
full or part time employment stat                  8
capital gains                                    132
capital losses                                   112
divdends from stocks                            1509
tax filer status                                   6
region of previous residence                       6
state of previous residence                       50
detailed household and family stat                38
detailed household summary in household            8
migration code-change in msa                       9
migration code-change in reg                       8
migration code-move within reg                     9
live in this house 1 year ago                      3
migration prev res in sunbelt                      3
num persons worked for employer                    7
family members under 18                            5
country of birth father                           42
country of birth mother                           42
country of birth self                             42
citizenship                                        5
own business or self employed                      3
fill inc questionnaire for veteran's admin         3
veterans benefits                                  3
weeks worked in year                              53
YEAR                                               2
TARGET                                             2
dtype: int64

In [29]:
df.TARGET.unique()

array([0, 1])

In [30]:
missing_values_info = df.isna().sum() / len(df) * 100
missing_values_info

ID                                             0.000000
age                                            0.000000
class of worker                                0.000000
industry code                                  0.000000
occupation code                                0.000000
education                                      0.000000
wage per hour                                  0.000000
enrolled in edu inst last wk                   0.000000
marital status                                 0.000000
major industry code                            0.000000
major occupation code                          0.000000
race                                           0.000000
hispanic origin                                0.000000
gender                                         0.000000
member of a labor union                        0.000000
reason for unemployment                        0.000000
full or part time employment stat              0.000000
capital gains                                  0.000000
capital losses                                 0.000000
divdends from stocks                           0.000000
tax filer status                               0.000000
region of previous residence                   0.000000
state of previous residence                    0.444419
detailed household and family stat             0.000000
detailed household summary in household        0.000000
migration code-change in msa                  49.089258
migration code-change in reg                  49.089258
migration code-move within reg                49.089258
live in this house 1 year ago                  0.000000
migration prev res in sunbelt                 49.089258
num persons worked for employer                0.000000
family members under 18                        0.000000
country of birth father                        4.192141
country of birth mother                        3.814385
country of birth self                          2.219556
citizenship                                    0.000000
own business or self employed                  0.000000
fill inc questionnaire for veteran's admin     0.000000
veterans benefits                              0.000000
weeks worked in year                           0.000000
YEAR                                           0.000000
TARGET                                         0.000000
dtype: float64

In [31]:
df.columns

Index(['ID', 'age', 'class of worker', 'industry code', 'occupation code',
       'education', 'wage per hour', 'enrolled in edu inst last wk',
       'marital status', 'major industry code', 'major occupation code',
       'race', 'hispanic origin', 'gender', 'member of a labor union',
       'reason for unemployment', 'full or part time employment stat',
       'capital gains', 'capital losses', 'divdends from stocks',
       'tax filer status', 'region of previous residence',
       'state of previous residence', 'detailed household and family stat',
       'detailed household summary in household',
       'migration code-change in msa', 'migration code-change in reg',
       'migration code-move within reg', 'live in this house 1 year ago',
       'migration prev res in sunbelt', 'num persons worked for employer',
       'family members under 18', 'country of birth father',
       'country of birth mother', 'country of birth self', 'citizenship',
       'own business or self employed',
       'fill inc questionnaire for veteran's admin', 'veterans benefits',
       'weeks worked in year', 'YEAR', 'TARGET'],
      dtype='object')

In [32]:
['ID', 'age', 'class of worker', 'industry code', 'occupation code',
       'education', 'wage per hour', 'enrolled in edu inst last wk',
       'marital status', 'major industry code', 'major occupation code',
       'race', 'hispanic origin', 'gender', 'member of a labor union',
       'reason for unemployment', 'full or part time employment stat',
       'capital gains', 'capital losses', 'divdends from stocks',
       'tax filer status', 'region of previous residence',
       'state of previous residence', 'detailed household and family stat',
       'detailed household summary in household',
       'migration code-change in msa', 'migration code-change in reg',
       'migration code-move within reg', 'live in this house 1 year ago',
       'migration prev res in sunbelt', 'num persons worked for employer',
       'family members under 18', 'country of birth father',
       'country of birth mother', 'country of birth self', 'citizenship',
       'own business or self employed',
       "fill inc questionnaire for veteran's admin", 'veterans benefits',
       'weeks worked in year', 'YEAR', 'TARGET']

['ID',
 'age',
 'class of worker',
 'industry code',
 'occupation code',
 'education',
 'wage per hour',
 'enrolled in edu inst last wk',
 'marital status',
 'major industry code',
 'major occupation code',
 'race',
 'hispanic origin',
 'gender',
 'member of a labor union',
 'reason for unemployment',
 'full or part time employment stat',
 'capital gains',
 'capital losses',
 'divdends from stocks',
 'tax filer status',
 'region of previous residence',
 'state of previous residence',
 'detailed household and family stat',
 'detailed household summary in household',
 'migration code-change in msa',
 'migration code-change in reg',
 'migration code-move within reg',
 'live in this house 1 year ago',
 'migration prev res in sunbelt',
 'num persons worked for employer',
 'family members under 18',
 'country of birth father',
 'country of birth mother',
 'country of birth self',
 'citizenship',
 'own business or self employed',
 "fill inc questionnaire for veteran's admin",
 'veterans benefits',
 'weeks worked in year',
 'YEAR',
 'TARGET']

## Value Count Function

## Filling ? values

## Feature Engineering

## Exploratory Data Analysis

In [33]:
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

## Subsetting the original dataframe for modelling

# The Middle - All about models

In [34]:
from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=40)

## Model Building

## Feature Scaling

# The End - All about submission

Inference :
* Piciking the best model for inference which is RandomForest

XTest = test_df.drop(columns=['ID'])

ytest_pred = trained_models['random_forest']['model'].predict(XTest)

output = sample_sub.copy()
output['TARGET'] = ytest_pred
output.head()

output['TARGET'].value_counts()/len(output)

output.to_csv('./solution.csv', index=False)